### ISSUE TITLE
Products not shown up under custom type products

### ISSUE THREAD

**Issue by Krishnakumar-c** [mrkhoa99/Boolfly_ProductRelation#1]
Once we added products it wont shown up in admin side under custom type products. I am working on magento 2.1.2. If we look in to the table products are there.

**Comment by mrkhoa99** [comment]
@Krishnakumar-c I'm working on this issue now. Also welcome any pull request.

**Comment by Krishnakumar-c** [comment]
How can we retrieve these products in view page, do we need to create any custom block ?

**Comment by mrkhoa99** [comment]
@Krishnakumar-c
Take a look at : `app/code/Boolfly/ProductRelation/Model/Product/Link/CollectionProvider/CustomType.php`, we can retrieve these products: `$product->getCustomTypeProducts();`. 
I also fixed the products not show up in admin side. Please, help me to check again.

**Comment by Krishnakumar-c** [comment]
@mrkhoa99 : I am trying to display these products in view page along with Related and upsell products, but dont getting the $block->getType() as customtype, only shows related,upsell in
app/design/frontend/vendor/winter/Magento_Catalog/templates/product/list/items.phtml.
 How can we get our customtype and products here ?

**Comment by mrkhoa99** [comment]
@Krishnakumar-c tomorrow, I will check this issue again.

**Comment by Krishnakumar-c** [comment]
Thanks @mrkhoa99 , There is no issue, actually I added a new block **product** for listing custom type products in view page, and it works.
